version: "3"

services:
  dbserver:
    build:
      context: ./db
      dockerfile: .Dockerfile
    volumes:
     - /var/lib/postgresql/data
    networks:
      - main-network
    environment:
      POSTGRES_PASSWORD: docker
      POSTGRES_USER: docker

  data_source:
    build:
      context: ./data_source
      dockerfile: .Dockerfile
    depends_on:
      - dbserver
    networks:
      - main-network

networks:
  main-network:
    driver: bridge