version: "3"

services:
  dbserver:
    build:
      context: ./db
      dockerfile: Dockerfile
    volumes:
     - /var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: docker
      POSTGRES_USER: docker

  data_source:
    build:
      context: ./data_source
      dockerfile: Dockerfile
    depends_on:
      - dbserver

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    depends_on:
      - data_source
      - dbserver
    ports:
      - 80:80
    environment:
      MAPS_API_KEY: 414d354acb344126b56c4642315f0f91
      JWT_KEY: ee3bdc7d363b15bf6863460b0b25523f9e6a3043d7ddf837ae5a3fc58f246e99

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      - api
    ports:
      - 8080:8080
